### ISSUE TITLE
Vulkan mod support?

### ISSUE THREAD

**Issue by Zorklis** [Relism/PortForwarded#1]
Currently I don't think it's working.
I load minecraft, turn on LAN and nothing happens, mod doesn't even appear in mod menu either [mod is in mod folder].

**Comment by Relism** [comment]
> Currently I don't think it's working.
> 
> I load minecraft, turn on LAN and nothing happens, mod doesn't even appear in mod menu either [mod is in mod folder].

Hey, are you installing this mod on the server or on the client ? this is a serverside only mod, it will not work on the client (vulkan mod is a clientside mode so i assume you're trying to load the mod client side)

**Comment by Zorklis** [comment]
Trying it without Vulkan mod also gave no results..

Wait is this not just like [Ngrok LAN](https://modrinth.com/mod/ngrok-lan) and requires like a proper server set up? Damn if so

**Comment by Relism** [comment]
> Trying it without Vulkan mod also gave no results..
> 
> 
> 
> Wait is this not just like [Ngrok LAN](https://modrinth.com/mod/ngrok-lan) and requires like a proper server set up? Damn if so

Yes that was clearly stated in both the readme and description
