### ISSUE TITLE
Config syntax is unclear 

### ISSUE THREAD

**Issue by LeNooby09** [Relism/PortForwarded#3]
`ngrok_region: EU`
Returns that ngrok automatically chooses the server with the lowest latency and that this (syntax) is deprecated.
`ngrok_region: [EU]`
Returns invalid region code(s)
`ngrok_region: [EU, US, ...](default)`
Also returns invalid region codes

Server:
Fabric 1.16.5
Java:
openjdk-17-internal

**Comment by Relism** [comment]
Hey! I honestly also noticed that, the config syntax is being remade from the ground up for the upcoming version..
